#ifndef _C_RANDOM_H_
#define _C_RANDOM_H_

	#include "random.h"

//	#define RANDOM_ENTROPY_SOURCE 		RANDOM_ENTROPY_SOURCE_AD_NOISE
	#define RANDOM_ENTROPY_SOURCE 		RANDOM_ENTROPY_SOURCE_TIME_JITTER_BUFFER
	#define RANDOM_ENTROPY_FLATTENER	RANDOM_ENTROPY_FLATTENER_SHA256
	#define RANDOM_AD_CHANNEL 0


#endif
